public without sharing class NTV_GlobalConstants {
  public static final String WHITE_SPACE = ' ';
  public static final String COMMA_SEPRATOR = ',';
  public static final String QUOTE_SEPRATOR = '\'';
  public static final String HYPHEN_SEPRATOR = '-';
  public static final String OPEN_PARANTHESIS = '(';
  public static final String CLOSE_PARANTHESIS = ')';
  public static final String OPEN_BRACE = '{';
  public static final String CLOSE_BRACE = '}';
  public static final String TRUE_LITERAL = 'TRUE';
  public static final String FALSE_LITERAL = 'FALSE';
  public static final String NULL_LITERAL = 'NULL';
  public static final String METHOD_POST = 'POST';
  public static final String METHOD_GET = 'GET';
  public static final String METHOD_PUT = 'PUT';
  public static final String METHOD_DELETE = 'DELETE';
}